### ISSUE TITLE
Numerous issues

### ISSUE THREAD

**Issue by mslinn** [xdotai/safe#9]
The repo below (safe branch) uses almost every feature of safe. If you try to compile, there will be numerous errors.

https://github.com/mslinn/quill-cache/tree/safe

**Comment by cvogt** [comment]
So one of the issues you are seeing is a limitation of safe"..." reported here https://github.com/xdotai/safe/issues/6

the workaround is calling .safeMkString explicitly

We could imagine lifting this restriction with overloads or macros

Other errors I am seeing, seem to be limitations of the applicability of safeContains or safeMkString. safeContains is defined on Seq, not String, Array or Options and implicit conversions to Seq are not automatically applied. We may be able to lift that. 

If you submit test cases in saprate PRs for the issues, ideally with fixes I am happy to merge them. I may also be able to contribute some fixes if I get the test cases.

Otherwise we'll extend this library only based on our own use cases. So while it would make sense to implement features that lift some of the above restrictions, this is not something we'd necessarily do. Closing this for now.

**Comment by cvogt** [comment]
Here are the error messages for further reference:
<details>

```
[error] quill-cache/src/main/scala/model/persistence/CacheLike.scala:12: Could not automatically convert java.io.Serializable to String. Did you mean to convert? If yes, consider converting manually or implementing a SafeToString[java.io.Serializable] type class instance or making java.io.Serializable extend trait SafeString.
[error]     Logger.debug(safe"Removing $id from $className cache")
[error]                  ^
[error] quill-cache/src/main/scala/model/persistence/CacheLike.scala:19: Could not automatically convert java.io.Serializable to String. Did you mean to convert? If yes, consider converting manually or implementing a SafeToString[java.io.Serializable] type class instance or making java.io.Serializable extend trait SafeString.
[error]     Logger.trace(safe"Added $i to $className cache")
[error]                  ^
[error] quill-cache/src/main/scala/model/persistence/CachedPersistence.scala:20: type mismatch;
[error]  found   : None.type
[error]  required: _IdType
[error]           case x if x === None => // new entity; insert it and return modified entity
[error]                           ^
[error] quill-cache/src/main/scala/model/persistence/CachedPersistence.scala:38: Could not automatically convert java.io.Serializable to String. Did you mean to convert? If yes, consider converting manually or implementing a SafeToString[java.io.Serializable] type class instance or making java.io.Serializable extend trait SafeString.
[error]     } Logger.trace(safe"Found $id in $className cache")
[error]                    ^
[error] quill-cache/src/main/scala/model/persistence/CachedPersistence.scala:42: Could not automatically convert java.io.Serializable to String. Did you mean to convert? If yes, consider converting manually or implementing a SafeToString[java.io.Serializable] type class instance or making java.io.Serializable extend trait SafeString.
[error]         Logger.trace(safe"Found $id in $className cache")
[error]                      ^
[error] quill-cache/src/main/scala/model/persistence/CachedPersistence.scala:51: Could not automatically convert java.io.Serializable to String. Did you mean to convert? If yes, consider converting manually or implementing a SafeToString[java.io.Serializable] type class instance or making java.io.Serializable extend trait SafeString.
[error]         Logger.debug(safe"Attempting to fetch $className #$id from database")
[error]                      ^
[error] quill-cache/src/main/scala/model/persistence/CachedPersistence.scala:55: Could not automatically convert java.io.Serializable to String. Did you mean to convert? If yes, consider converting manually or implementing a SafeToString[java.io.Serializable] type class instance or making java.io.Serializable extend trait SafeString.
[error]             Logger.debug(safe"Caching $className #$id")
[error]                          ^
[error] quill-cache/src/main/scala/model/persistence/ProcessEvolutionUp.scala:12: value safeContains is not a member of String
[error]     line.toLowerCase.replaceAll("\\s+", " ").safeContains(target)
[error]                                              ^
[error] quill-cache/src/main/scala/model/persistence/ProcessEvolutionUp.scala:20: not found: value safeContains
[error]       .dropWhile(!safeContains(_, "# --- !Ups".toLowerCase))
[error]                   ^
[error] quill-cache/src/main/scala/model/persistence/ProcessEvolutionUp.scala:22: not found: value safeContains
[error]       .takeWhile(!safeContains(_, "# --- !Downs".toLowerCase))
[error]                   ^
[error] quill-cache/src/main/scala/model/persistence/QuillImplicits.scala:58: value safeMkString is not a member of Option[java.net.URL]
[error]   implicit val encodeOptionURL: MappedEncoding[Option[URL], String] = MappedEncoding[Option[URL], String](_.safeMkString)
[error]                                                                                                             ^
[error] quill-cache/src/main/scala/model/persistence/UnCachedPersistence.scala:52: type mismatch;
[error]  found   : None.type
[error]  required: _IdType
[error]           case x if x===None => // new entity; insert it and return modified entity
[error]                         ^
[error] quill-cache/src/main/scala/model/persistence/UnCachedPersistence.scala:60: Could not automatically convert java.io.Serializable to String. Did you mean to convert? If yes, consider converting manually or implementing a SafeToString[java.io.Serializable] type class instance or making java.io.Serializable extend trait SafeString.
[error]     Logger.debug(safe"Deleting $className #${ caseClass.id } from database and cache")
[error]                  ^
[error] quill-cache/src/main/scala/model/persistence/UnCachedPersistence.scala:66: Could not automatically convert java.io.Serializable to String. Did you mean to convert? If yes, consider converting manually or implementing a SafeToString[java.io.Serializable] type class instance or making java.io.Serializable extend trait SafeString.
[error]     Logger.debug(safe"Deleting $className #$id from database and cache")
[error]                  ^
[error] quill-cache/src/main/scala/model/persistence/UnCachedPersistence.scala:84: Could not automatically convert Any to String. Did you mean to convert? If yes, consider converting manually or implementing a SafeToString[Any] type class instance or making Any extend trait SafeString.
[error]       Logger.trace(safe"Fetched all ${ caseClasses.size } ${ className }s from database")
[error]                    ^
[error] quill-cache/src/main/scala/model/persistence/UnCachedPersistence.scala:110: type mismatch;
[error]  found   : None.type
[error]  required: _IdType
[error]     case x if x===None => ()
[error]                   ^
[warn] quill-cache/src/main/scala/model/persistence/UnCachedPersistence.scala:119: a type was inferred to be `Any`; this may indicate a programming error.
[warn]   @inline def setAutoInc(): Unit = if (ctx.isInstanceOf[PostgresJdbcContext[_]]) try {
[warn]                                                                                  ^
[error] quill-cache/src/main/scala/model/persistence/UnCachedPersistence.scala:121: Could not automatically convert Any to String. Did you mean to convert? If yes, consider converting manually or implementing a SafeToString[Any] type class instance or making Any extend trait SafeString.
[error] Error occurred in an application involving default arguments.
[error]     ctx.executeAction(safe"ALTER SEQUENCE ${ tableName }_id_seq RESTART WITH ${ maxId + 1L }")
[error]                       ^
[error] quill-cache/src/main/scala/model/persistence/UnCachedPersistence.scala:136: Could not automatically convert CaseClass to String. Did you mean to convert? If yes, consider converting manually or implementing a SafeToString[CaseClass] type class instance or making CaseClass extend trait SafeString.
[error]         Logger.error(safe"upsert $caseClass" + ex.format())
[error]                      ^
[error] quill-cache/src/main/scala/model/persistence/package.scala:168: value === is not a member of Null
[error]       val noMessage = (null===message) || message.trim.isEmpty
[error]                            ^
[error] quill-cache/src/main/scala/model/persistence/package.scala:170: Could not automatically convert Throwable to String. Did you mean to convert? If yes, consider converting manually or implementing a SafeToString[Throwable] type class instance or making Throwable extend trait SafeString.
[error]       (if (noCause) "" else safe"$cause: ") + (if (noMessage) "" else message) +
[error]                             ^
[error] quill-cache/src/main/scala/model/persistence/package.scala:173: value safeMkString is not a member of Array[StackTraceElement]
[error]             "\n<pre>" + ex.getStackTrace.safeMkString("\n  ", "\n  ", "\n") + "</pre>\n"
[error]                                          ^
[error] quill-cache/src/main/scala/model/persistence/package.scala:177: value safeMkString is not a member of Array[StackTraceElement]
[error]           (if (showStackTrace || (noCause && noMessage)) ex.getStackTrace.safeMkString("\n  ") else "")
[error]
```

</details>

**Comment by mslinn** [comment]
I looked into the approaches to the `safe` issues that you pointed out, and made some progress, but `safe` uses `cbt`, which requires that I disable the IntelliJ Scala plugin. Is there any way to have two instances of IDEA running, one using CBT and one using SBT?

**Comment by cvogt** [comment]
The CBT plugin is a fork of the Scala plugin that includes SBT support. So just using that should be fine.

**Comment by mslinn** [comment]
`Plugin 'Scala' is incompatible with this installation`. I'm using IDEA Ultimate 2017.1.2

**Comment by cvogt** [comment]
Mh, No clue. @darthorimar may be able to help.

Otherwise maybe just command line? It's a single file + a test file.

**Comment by darthorimar** [comment]
@mslinn, @cvogt I've updated supported versions range in plugin. Still not sure it will work on 2017.1. If it would work please tell, in that case I'll update it in readme
https://www.dropbox.com/s/gcb81spuuozv5st/scala-plugin171.zip?dl=0

**Comment by mslinn** [comment]
The new plugin (v1.71) installed, and reports as the Scala plugin, which is confusing. Also, upon reboot, IDEA offers to update the Scala plugin, which would replace the modified version for CBT with the standard Scala plugin. It would be better if the CBT plugin somehow extended the Scala plugin, instead of replacing it.

**Comment by darthorimar** [comment]
I hope the CBT support will be merged into the core scala plugin in the future. And for now I'll try to avoid such behaviour.
